// SPDX-License-Identifier: MIT-0
// SPDX-FileCopyrightText:  2026 Istvan Pasztor

package main

import (
	"fmt"
	"hash"
	"strings"
	"testing"
	"time"
)

func TestTOTP(t *testing.T) {
	type TimeAndOTP struct {
		UnixTime        int64
		OneTimePassword string
	}

	// These test cases were generated by turning the URIs into QR codes, adding
	// them to Google Authenticator, and watching the current time along with
	// the codes generated by Google Authenticator.
	testCases := []struct {
		URI   string
		Tests []TimeAndOTP
	}{
		{
			URI: "otpauth://totp/LABEL?secret=M3B3Y43UYO3GY5BAONXW423BEAVSAZWFSF2HIIDUN5VMHILT&digits=6&period=30&algorithm=SHA1&issuer=me",
			Tests: []TimeAndOTP{
				{UnixTime: 1776982590, OneTimePassword: "107858"},
				{UnixTime: 1776982619, OneTimePassword: "107858"},
				{UnixTime: 1776982620, OneTimePassword: "127981"},
				{UnixTime: 1776982649, OneTimePassword: "127981"},
				{UnixTime: 1776982650, OneTimePassword: "326036"},
				{UnixTime: 1776982679, OneTimePassword: "326036"},
				{UnixTime: 1776982680, OneTimePassword: "721374"},
			},
		},
		{
			URI: "otpauth://totp/LABEL?secret=M3B3Y43UYO3GY5BAONXW423BEAVSAZWFSF2HIIDUN5VMHILT&digits=6&period=60&algorithm=SHA256&issuer=me",
			Tests: []TimeAndOTP{
				{UnixTime: 1776983100, OneTimePassword: "058320"},
				{UnixTime: 1776983159, OneTimePassword: "058320"},
				{UnixTime: 1776983160, OneTimePassword: "249418"},
				{UnixTime: 1776983219, OneTimePassword: "249418"},
				{UnixTime: 1776983220, OneTimePassword: "955029"},
				{UnixTime: 1776983279, OneTimePassword: "955029"},
				{UnixTime: 1776983280, OneTimePassword: "282277"},
			},
		},
		{
			URI: "otpauth://totp/LABEL?secret=M3B3Y43UYO3GY5BAONXW423BEAVSAZWFSF2HIIDUN5VMHILT&digits=8&period=30&algorithm=SHA512&issuer=me",
			Tests: []TimeAndOTP{
				{UnixTime: 1776983490, OneTimePassword: "68907093"},
				{UnixTime: 1776983519, OneTimePassword: "68907093"},
				{UnixTime: 1776983520, OneTimePassword: "25534620"},
				{UnixTime: 1776983549, OneTimePassword: "25534620"},
				{UnixTime: 1776983550, OneTimePassword: "78016921"},
				{UnixTime: 1776983579, OneTimePassword: "78016921"},
				{UnixTime: 1776983580, OneTimePassword: "86592464"},
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.URI, func(t *testing.T) {
			totp, err := parseURI(tc.URI)
			requireNoError(t, err)

			for _, subTest := range tc.Tests {
				pw := totp.Generate(time.Unix(subTest.UnixTime, 0))
				assertEqual(t, subTest.OneTimePassword, pw, "wrong one-time password")
			}
		})
	}
}

func TestParseSecretOrURI(t *testing.T) {
	t.Run("secret key", func(t *testing.T) {
		totp, err := parseSecretOrURI("HE4DONRVGQZTEMJQHE4DONRVGQZTEMJQ")
		requireNoError(t, err)
		requireTOTP(t, []byte("98765432109876543210"), sha1Signature, 6, 30, totp)
	})

	t.Run("uri", func(t *testing.T) {
		totp, err := parseSecretOrURI("otpauth://totp/LABEL?secret=HE4DONRVGQZTEMJQHE4DONRVGQZTEMJQ&algorithm=SHA512")
		requireNoError(t, err)
		requireTOTP(t, []byte("98765432109876543210"), sha512Signature, 6, 30, totp)
	})
}

func TestParseSecret(t *testing.T) {
	t.Run("no base32 padding needed", func(t *testing.T) {
		// base32 string length is a multiple of 8, so no padding needed
		totp, err := parseSecret("HE4DONRVGQZTEMJQHE4DONRVGQZTEMJQ")
		requireNoError(t, err)
		requireTOTP(t, []byte("98765432109876543210"), sha1Signature, 6, 30, totp)
	})

	t.Run("base32 with padding", func(t *testing.T) {
		// base32 string length isn't a multiple of 8
		totp, err := parseSecret("HE4DONRVGQZTEMJQHE4DONRVGQZTE===")
		requireNoError(t, err)
		requireTOTP(t, []byte("987654321098765432"), sha1Signature, 6, 30, totp)
	})

	t.Run("base32 without padding", func(t *testing.T) {
		// base32 string length isn't a multiple of 8
		totp, err := parseSecret("HE4DONRVGQZTEMJQHE4DONRVGQZTE")
		requireNoError(t, err)
		requireTOTP(t, []byte("987654321098765432"), sha1Signature, 6, 30, totp)
	})

	t.Run("whitespace characters are allowed and ignored", func(t *testing.T) {
		totp, err := parseSecret("HE4D ONRV GQZT EMJQ HE4D ONRV GQZT EMJQ")
		requireNoError(t, err)
		requireTOTP(t, []byte("98765432109876543210"), sha1Signature, 6, 30, totp)
	})
}

func TestParseURI(t *testing.T) {
	t.Run("specify secret parameter only", func(t *testing.T) {
		totp, err := parseURI("otpauth://totp/LABEL?secret=HE4DONRVGQZTEMJQ")
		requireNoError(t, err)
		requireTOTP(t, []byte("9876543210"), sha1Signature, 6, 30, totp)
	})

	t.Run("specify all optional parameters", func(t *testing.T) {
		totp, err := parseURI("otpauth://totp/LABEL?secret=HE4DONRVGQZTEMJQ&digits=8&period=60&algorithm=SHA256&issuer=me")
		requireNoError(t, err)
		requireTOTP(t, []byte("9876543210"), sha256Signature, 8, 60, totp)
	})

	t.Run("empty secret", func(t *testing.T) {
		_, err := parseURI("otpauth://totp/LABEL?secret=")
		requireError(t, err, "empty secret")
	})

	t.Run("missing secret", func(t *testing.T) {
		_, err := parseURI("otpauth://totp/LABEL?")
		requireError(t, err, "empty secret")
	})
}

func requireTOTP(t *testing.T, secret []byte, algorithmSignature string, digits, period int, totp *TOTP) {
	t.Helper()
	assertEqual(t, string(secret), string(totp.Secret), "wrong secret")
	assertEqual(t, digits, totp.Digits, "wrong digits")
	assertEqual(t, period, totp.Period, "wrong period")
	expectAlgorithm(t, algorithmSignature, totp.Algorithm)
}

const (
	sha1Signature   = "87acec17"
	sha256Signature = "84d89877"
	sha512Signature = "bb96c2fc"
)

// expectAlgorithm checks if a hash constructor function is backed by the expected algorithm.
// Golang doesn't allow us to compare function pointers, so instead, we execute
// the hashing algorithm on a known input, and check its output.
func expectAlgorithm(t *testing.T, expectedSignature string, algorithm func() hash.Hash) {
	t.Helper()

	h := algorithm()
	h.Write([]byte("0123456789"))
	signature := fmt.Sprintf("%x", h.Sum(nil)[:4])

	assertEqual(t, expectedSignature, signature, "wrong algorithm")
}

func requireNoError(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}
}

func requireError(t *testing.T, err error, expectedMsg string) {
	t.Helper()
	if err == nil {
		t.Fatal("Expected an error, but got nil")
	}
	if expectedMsg != "" && !strings.Contains(err.Error(), expectedMsg) {
		t.Fatalf("Expected error message to contain %q, but got %q", expectedMsg, err.Error())
	}
}

func assertEqual[T comparable](t *testing.T, expected, actual T, msg string) {
	t.Helper()
	if expected != actual {
		t.Errorf("%s: expected %v, got %v", msg, expected, actual)
	}
}
